CREATE TABLE IF NOT EXISTS AUTH.USERS (
    ID SERIAL4 PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(100),
    BIRTHDATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);